name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: PhuocHoan
          template: classic
          filename: github-metrics.svg
        
          base: repositories, metadata
          config_timezone: Asia/Ho_Chi_Minh
          
          config_display: regular
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot,
            vue, jupyter notebook, java, javascript, typescript, c++, python, c, shell
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: bytes-size, percentage
          
          plugin_isocalendar: no
